config/routes.rb
TweetsOnUs::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  

    resources :tweets, only:[:index]
    resources :groups, only:[:index]
    
    get '/auth/:provider/callback', to: 'sessions#create'
    get '/auth/invalid', to: 'sessions#invalid'
    get 'signout', to: 'sessions#destroy', as: 'signout'
    root 'welcome#index'

  

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :tweeters,
    through: :tweeter_groups
  has_many :tweeter_groups

  validates_presence_of :tag
  validates_uniqueness_of :tag

RailsAdmin.config {|c| c.label_methods << :tag}

  def tweet_count
    tweet_count = 0
    self.tweeters.each do |tweeter|
      tweet_count += tweeter.tweets.count
    end
    tweet_count
  end

  def self.tweeter_tweets_count
    group_tweet_count = {}
    self.all.each do |group|
      group_tweet_count[group.tag] = group.tweet_count
    end
    group_tweet_count
  end

  def self.tag_check(params)
    if params[:tag].present?
      @group = Group.where(id: params[:tag][:group_id]).first
    else
      nil
    end
  end

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  
  belongs_to :tweeter

  validates_presence_of :content
  validates_presence_of :tweet_date

  class << self

    def from_today
      Tweet.where(tweet_date: Date.today)
    end
    
  end
end

app/models/tweeter.rb
class Tweeter < ActiveRecord::Base
  has_many :groups,
    through: :tweeter_groups

  has_many :tweeter_groups

  has_many :tweets

  validates_presence_of :handle

  def self.handles
    handles = []
    Tweeter.all.each do |tweeter|
      handles << tweeter.handle
    end
    handles
  end

  def self.pull_handle_tweet
    #run worker for every handle
    Tweeter.all.each do |tweeter|
      TweeterWorker.perform_async(tweeter.id)
    end
  end

  def collect_with_max_id(collection=[], max_id=nil, &block)
    response = yield max_id
    collection += response
    response.empty? ? collection.flatten : collect_with_max_id(collection, response.last.id - 1, &block)
  end

  def fetch_all_tweets(user)
    collect_with_max_id do |max_id|
      options = {:count => 200, :include_rts => true}
      options[:max_id] = max_id unless max_id.nil?
      Twitter.user_timeline(user, options)
    end
  end

  validates_uniqueness_of :handle

  RailsAdmin.config {|c| c.label_methods << :handle}

    def handle_words
      handle_word_array = []
      self.tweets.each do |tweet|
        tweet.content.split(" ").each do |word|
          handle_word_array << word
        end
      end
      result = Hash.new(0)
      handle_word_array.each { |word| result[word] += 1 }
      return result
    end

    def self.handle_check(params)
      if params[:handle].present?
        @tweeter = Tweeter.where(id: params[:handle][:tweeter_id]).first
      else
        nil
      end
    end

end

app/models/tweeter_group.rb
class TweeterGroup < ActiveRecord::Base
  belongs_to :tweeter
  belongs_to :group
end

app/models/user.rb
class User < ActiveRecord::Base


  def self.from_omniauth(auth)
    user = where(auth.slice("provider", "uid")).first || create_from_omniauth(auth)
    user.oauth_token = auth["credentials"]["token"]
    user.oauth_secret = auth["credentials"]["secret"]
    user.save!
    user
  end
  
  def self.create_from_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["nickname"]
    end
  end

  def twitter
    if provider == "twitter"
      @twitter ||= Twitter::Client.new(oauth_token: oauth_token, oauth_token_secret: oauth_secret)
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def current_user
    if session[:user_id]
      @current_user = User.find(session[:user_id]) if User.where(id: session[:user_id]).any?
    end
    # @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @group_tweets = Group.tweeter_tweets_count
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def create
   user = User.from_omniauth(env['omniauth.auth'])
   session[:user_id] = user.id
   redirect_to root_url, notice: "Signed in."
  end

  def destroy
  session[:user_id] = nil
  redirect_to root_url, notice: "Signed out."
  end
  
  def invalid
    session[:user_id] = nil
    redirect_to root_url, notice: "Authentication failed, please try again."
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets_from_today = Tweet.from_today
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @tweeter = Tweeter.handle_check(params)
    @group = Group.tag_check(params)
    @group_tweets = Group.tweeter_tweets_count
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/groups/index.html.erb
<%= pie_chart @group_tweets %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TweetsOnUs</title>
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
</head>
<body>

  <div class="container">
    <ul class="nav nav-tabs pull-left">
      <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Home", root_path %></li>
      <% if current_user.present? && current_user.role == "admin" %>
        <li class="<%= 'active' if current_page?(rails_admin_path) %>"><%= link_to "Admin", rails_admin_path %></li>
      <% end %>
    </ul>

    <ul class="nav nav-tabs pull-right">
      <% if current_user %>
        <li><a href="https://twitter.com/#{current_user.name}"><%= current_user.name %></a></li>
        <li><%= link_to "Sign out", signout_path %></li>
      <% else %>
        <li><%= link_to "Sign in with Twitter", "/auth/twitter"%></li>
      <% end %>
    </ul>
  </div>

  <div class="container">
    <% flash.each do |name, msg| %>
      <div class="alert-info" data-alert="alert">
      <a class="close" data-dismiss='alert' href="#">×</a>
      <%= content_tag :div, msg, id: "flash_#{name}" %>
    <% end %>
    </div>
  </div>

  <%= yield %>


  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <%= yield :extra_footer %>
</body>


</html>

app/views/welcome/_tweet_group_stats.html.erb
<div class="hero box_one">
  <div class="container">
    <div align="center">
      <div class="row center">

        <div class="span4 pull-left">
          <h2>Groups</h2>
          <%= form_tag("/", method: "get") do %>
            <%= collection_select(:tag, :group_id, Group.all, :id, :tag, {selected: @group.id}) %>
            <br>
            <%= submit_tag("Update Group", class: "btn") %>
          <% end %>
        </div>

        <div class="span4 pull-right">
          <h2>Handles</h2>
          <%= form_tag("/", method: "get") do %>
            <%= collection_select(:handle, :tweeter_id, Tweeter.all, :id, :handle,{selected: nil}) %>
            <br>
            <%= submit_tag("Update Handle", class: "btn") %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="tweet_table">
      <table class="table table-bordered table-striped">
      <thead>
        <tr class="tweet_header">
          <th>Handle</th>
          <th>Tweet</th>
          <th>Date</th>
        </tr>
      </thead>
      <% @group.tweeters.each do |tweeter| %>
        <% tweeter.tweets.each do |tweet| %>
          <tbody>
            <tr>
              <td>
                <%= "@#{tweet.tweeter.handle}" %>
              </td>
              <td><%= tweet.content %>
                <a href="#" class="retweet"><i class="icon-retweet"></i></a>
              </td>
              <td>
                <%= tweet.tweet_date %>
              </td>
            </tr>
          </tbody>
          <% end %>
      <% end %>
    </table>
    </div>
  </div>
</div>

<div class="hero box_two">
  <div class="container">
    <div align="center">
      <h2><%= "#{@group.tag}" %></h2>
    </div>
    <div class="white_box center">
      <div id="tweet_cloud" style="width: 550px; height: 350px;">
      </div>
    </div>
  </div>
</div>

<div class="hero box_three">
  <div class="container">
    <div align="center">
      <h2><%= "#{@group.tag}" %></h2>
    </div>
    <div class="pie_chart center">
      <%= pie_chart @group_tweets %>
    </div>
  </div>
</div>

<% content_for :extra_footer do %>
    <script>
        var word_array = [];
        "<% @group.tweeters.each do |tweeter| %>"
          "<% tweeter.handle_words.each do |word, value| %>"
            word_array.push({text: "<%= word %>", weight: "<%= value %>"});
          "<% end %>"
        "<% end %>"

        $(function() {
          $("#tweet_cloud").jQCloud(word_array);
        });
    </script>
<% end %>

app/views/welcome/_tweet_handle_stats.html.erb
<div class="hero box_one">
  <div class="container">
    <div align="center">
      <div class="row center">

        <div class="span4 pull-left">
          <h2>Groups</h2>
          <%= form_tag("/", method: "get") do %>
            <%= collection_select(:tag, :group_id, Group.all, :id, :tag, {selected: nil}) %>
            <br>
            <%= submit_tag("Update Group", class: "btn group_submit") %>
          <% end %>
        </div>

        <div class="span4 pull-right">
          <h2>Handles</h2>
          <%= form_tag("/", method: "get") do %>
            <%= collection_select(:handle, :tweeter_id, Tweeter.all, :id, :handle,{selected: @tweeter.id}) %>
            <br>
            <%= submit_tag("Update Handle", class: "btn") %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="tweet_table">
      <table class="table table-bordered table-striped">
      <thead>
        <tr class="tweet_header">
          <th>Handle</th>
          <th>Tweet</th>
          <th>Date</th>
        </tr>
      </thead>
      <% @tweeter.tweets.each do |tweet| %>
      <tbody>
        <tr>
          <td>
            <%= "@#{tweet.tweeter.handle}" %>
          </td>
          <td><%= tweet.content %>
            <a href="#" class="retweet"><i class="icon-retweet"></i></a>
          </td>
          <td>
            <%= tweet.tweet_date %>
          </td>
        </tr>
      </tbody>
      <% end %>
    </table>
    </div>
  </div>
</div>

<div class="hero box_two">
  <div class="container">
    <div align="center">
      <h2>@<%= "#{@tweeter.handle}" %></h2>
    </div>
    <div class="white_box center">
      <div id="tweet_cloud" style="width: 550px; height: 350px;">
      </div>
    </div>
  </div>
</div>

<div class="hero box_three">
  <div class="container">
    <div align="center">
      <h2>@<%= "#{@tweeter.handle}" %></h2>
    </div>
    <div class="pie_chart center">
      <%= pie_chart @group_tweets %>
    </div>
  </div>
</div>

<% content_for :extra_footer do %>
    <script>
        var word_array = [];
        "<% @tweeter.handle_words.each do |word, value| %>"
          word_array.push({text: "<%= word %>", weight: "<%= value %>"});
        "<% end %>"

        $(function() {
          $("#tweet_cloud").jQCloud(word_array);
        });
    </script>
<% end %>

app/views/welcome/index.html.erb
      <% if @tweeter.present? %>
        <%= render 'tweet_handle_stats', local: {tweeter: @tweeter}  %>
      <% elsif @group.present? %>
        <%= render 'tweet_group_stats', local: {group: @group}  %>
      <% else %>

  <div class="hero box_one">
    <div class="container">
      <div align="center">
        <div class="row center">
          <h1 align="center"> Select a group or handle </h1>
          <div class="span4 pull-left">
            <h2>Groups</h2>
          <%= form_tag("/", method: "get") do %>
          <%= collection_select(:tag, :group_id, Group.all, :id, :tag, {selected: nil}) %>
          <br>
          <%= submit_tag("Update Group", class: "btn group_submit") %>
          <% end %>
          </div>

          <div class="span4 pull-right">
            <h2>Handles</h2>
              <%= form_tag("/", method: "get") do %>
              <%= collection_select(:handle, :tweeter_id, Tweeter.all, :id, :handle) %>
            <br>
            <%= submit_tag("Update Handle", class: "btn handle_submit") %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

<% end %>